In [2]:
import pandas as pd
df  = pd.read_excel("D:\\2020\\Python\\MTN\MAPS_Availbilty\\Input\\Hourly and National Regional Availability_new_2020031117_40f7e54eb61b49338a024de454c3787e.xlsx",skiprows=1)
df = df.set_index("REGION")
# df.iloc[0] = df.iloc[0].fillna(method='ffill', axis=1)
df.loc[:]
df.iloc[0]

2020-03-11 12:00:00            2G AVAIL(%)
Unnamed: 2                     3G AVAIL(%)
Unnamed: 3                     4G AVAIL(%)
2020-03-11 13:00:00            2G AVAIL(%)
Unnamed: 5                     3G AVAIL(%)
Unnamed: 6                     4G AVAIL(%)
2020-03-11 14:00:00            2G AVAIL(%)
Unnamed: 8                     3G AVAIL(%)
Unnamed: 9                     4G AVAIL(%)
2020-03-11 15:00:00            2G AVAIL(%)
Unnamed: 11                    3G AVAIL(%)
Unnamed: 12                    4G AVAIL(%)
Unnamed: 13                            NaN
Time                   2020-03-11 12:00:00
Country                            Nigeria
2G AVAIL(%)                          98.79
3G AVAIL(%)                          98.29
4G AVAIL(%)                          99.38
Name: nan, dtype: object

In [4]:
import pandas as pd
df  = pd.read_excel("D:\\2020\\Python\\MTN\MAPS_Availbilty\\Input\\Hourly and National Regional Availability_new_2020031117_40f7e54eb61b49338a024de454c3787e.xlsx",skiprows=1)
df = df.set_index("REGION")
# df.iloc[0] = df.iloc[0].fillna(method='ffill', axis=1)
df.loc[:]
# df.iloc[0]

,2020-03-11 12:00:00,Unnamed: 2,Unnamed: 3,2020-03-11 13:00:00,Unnamed: 5,Unnamed: 6,2020-03-11 14:00:00,Unnamed: 8,Unnamed: 9,2020-03-11 15:00:00,Unnamed: 11,Unnamed: 12,Unnamed: 13,Time,Country,2G AVAIL(%),3G AVAIL(%),4G AVAIL(%)
REGION,,,,,,,,,,,,,,,,,,
NaN,2G AVAIL(%),3G AVAIL(%),4G AVAIL(%),2G AVAIL(%),3G AVAIL(%),4G AVAIL(%),2G AVAIL(%),3G AVAIL(%),4G AVAIL(%),2G AVAIL(%),3G AVAIL(%),4G AVAIL(%),NaN,2020-03-11 12:00:00,Nigeria,98.79,98.29,99.38
ABJ,98.5022,98.7591,99.5229,98.9913,99.1147,99.5382,98.9648,98.8156,99.4417,98.9856,98.9342,99.6136,NaN,2020-03-11 13:00:00,Nigeria,98.75,98.30,99.45
ASB,99.0545,98.841,99.4089,98.8195,98.7032,99.6793,98.5846,98.5838,99.5104,98.3829,98.0231,99.2234,NaN,2020-03-11 14:00:00,Nigeria,98.76,98.12,99.43
ENG,99.0916,99.0027,99.6194,98.9045,98.8783,99.5615,99.0292,98.9379,99.6527,99.0426,98.7161,99.7299,NaN,2020-03-11 15:00:00,Nigeria,98.74,98.03,99.38
IBD,99.171,98.8402,99.5237,99.1699,99.1208,99.7586,99.2625,99.1924,99.771,99.2436,99.2321,99.8409,NaN,NaT,NaN,NaN,NaN,NaN
KNO,98.065,98.4485,99.3134,97.3755,98.0567,99.0537,97.4053,97.76,98.9076,97.1283,97.6146,98.9158,NaN,NaT,NaN,NaN,NaN,NaN
LGS,95.8561,96.5828,98.7698,95.7763,96.4874,98.8772,95.4111,96.1407,98.9094,95.7431,96.1184,98.5743,NaN,NaT,NaN,NaN,NaN,NaN
PHC,99.1917,99.2497,99.9129,99.3282,99.2136,99.9352,99.2953,99.1578,99.929,99.1989,99.0745,99.9905,NaN,NaT,NaN,NaN,NaN,NaN

In [17]:
import pandas as pd
nam = "Hourly and National Regional Availability_new_2020031117_40f7e54eb61b49338a024de454c3787e.xlsx"
df  = pd.read_excel(f"D:\\2020\\Python\\MTN\MAPS_Availbilty\\Input\\{nam}", index_col=None, na_values=['NA'], skiprows=1)
df = df.set_index("REGION")
# df.iloc[0] = df.iloc[0].fillna(method='ffill', axis=1)
# df.loc[1]
# df.iloc[:]
# df.columns = df.iloc[0].fillna(method='ffill')
df

,2020-03-11 12:00:00,Unnamed: 2,Unnamed: 3,2020-03-11 13:00:00,Unnamed: 5,Unnamed: 6,2020-03-11 14:00:00,Unnamed: 8,Unnamed: 9,2020-03-11 15:00:00,Unnamed: 11,Unnamed: 12,Unnamed: 13,Time,Country,2G AVAIL(%),3G AVAIL(%),4G AVAIL(%)
REGION,,,,,,,,,,,,,,,,,,
NaN,2G AVAIL(%),3G AVAIL(%),4G AVAIL(%),2G AVAIL(%),3G AVAIL(%),4G AVAIL(%),2G AVAIL(%),3G AVAIL(%),4G AVAIL(%),2G AVAIL(%),3G AVAIL(%),4G AVAIL(%),NaN,2020-03-11 12:00:00,Nigeria,98.79,98.29,99.38
ABJ,98.5022,98.7591,99.5229,98.9913,99.1147,99.5382,98.9648,98.8156,99.4417,98.9856,98.9342,99.6136,NaN,2020-03-11 13:00:00,Nigeria,98.75,98.30,99.45
ASB,99.0545,98.841,99.4089,98.8195,98.7032,99.6793,98.5846,98.5838,99.5104,98.3829,98.0231,99.2234,NaN,2020-03-11 14:00:00,Nigeria,98.76,98.12,99.43
ENG,99.0916,99.0027,99.6194,98.9045,98.8783,99.5615,99.0292,98.9379,99.6527,99.0426,98.7161,99.7299,NaN,2020-03-11 15:00:00,Nigeria,98.74,98.03,99.38
IBD,99.171,98.8402,99.5237,99.1699,99.1208,99.7586,99.2625,99.1924,99.771,99.2436,99.2321,99.8409,NaN,NaT,NaN,NaN,NaN,NaN
KNO,98.065,98.4485,99.3134,97.3755,98.0567,99.0537,97.4053,97.76,98.9076,97.1283,97.6146,98.9158,NaN,NaT,NaN,NaN,NaN,NaN
LGS,95.8561,96.5828,98.7698,95.7763,96.4874,98.8772,95.4111,96.1407,98.9094,95.7431,96.1184,98.5743,NaN,NaT,NaN,NaN,NaN,NaN
PHC,99.1917,99.2497,99.9129,99.3282,99.2136,99.9352,99.2953,99.1578,99.929,99.1989,99.0745,99.9905,NaN,NaT,NaN,NaN,NaN,NaN

In [70]:
import pandas as pd
nam = "Hourly and National Regional Availability_new_2020031117_40f7e54eb61b49338a024de454c3787e.xlsx"
df  = pd.read_excel(f"D:\\2020\\Python\\MTN\MAPS_Availbilty\\Input\\{nam}", index_col=None, na_values=['NA'], skiprows=1)
df = df.set_index("REGION")
# df

ml = df.columns.tolist()
# print(ml)

for i in ml:
    if "Unnamed" in i and "Time" not in ml[ml.index(i) + 1]:
        ml[ml.index(i)] = ml[ml.index(i) - 1]
df.columns = ml
df = df.iloc[:,:12]
df
# for each in df.index[1:]:
#     print(each)

,2020-03-11 12:00:00,2020-03-11 12:00:00,2020-03-11 12:00:00,2020-03-11 13:00:00,2020-03-11 13:00:00,2020-03-11 13:00:00,2020-03-11 14:00:00,2020-03-11 14:00:00,2020-03-11 14:00:00,2020-03-11 15:00:00,2020-03-11 15:00:00,2020-03-11 15:00:00
REGION,,,,,,,,,,,,
NaN,2G AVAIL(%),3G AVAIL(%),4G AVAIL(%),2G AVAIL(%),3G AVAIL(%),4G AVAIL(%),2G AVAIL(%),3G AVAIL(%),4G AVAIL(%),2G AVAIL(%),3G AVAIL(%),4G AVAIL(%)
ABJ,98.5022,98.7591,99.5229,98.9913,99.1147,99.5382,98.9648,98.8156,99.4417,98.9856,98.9342,99.6136
ASB,99.0545,98.841,99.4089,98.8195,98.7032,99.6793,98.5846,98.5838,99.5104,98.3829,98.0231,99.2234
ENG,99.0916,99.0027,99.6194,98.9045,98.8783,99.5615,99.0292,98.9379,99.6527,99.0426,98.7161,99.7299
IBD,99.171,98.8402,99.5237,99.1699,99.1208,99.7586,99.2625,99.1924,99.771,99.2436,99.2321,99.8409
KNO,98.065,98.4485,99.3134,97.3755,98.0567,99.0537,97.4053,97.76,98.9076,97.1283,97.6146,98.9158
LGS,95.8561,96.5828,98.7698,95.7763,96.4874,98.8772,95.4111,96.1407,98.9094,95.7431,96.1184,98.5743
PHC,99.1917,99.2497,99.9129,99.3282,99.2136,99.9352,99.2953,99.1578,99.929,99.1989,99.0745,99.9905

In [49]:
import pandas as pd
nam = "Hourly and National Regional Availability_new_2020031117_40f7e54eb61b49338a024de454c3787e.xlsx"
df  = pd.read_excel(f"D:\\2020\\Python\\MTN\MAPS_Availbilty\\Input\\{nam}", index_col=None, na_values=['NA'], skiprows=1)
df = df.set_index("REGION")
# df

ml = df.columns.tolist()
# print(ml)

for i in ml:
    if "Unnamed" in i and "Time" not in ml[ml.index(i) + 1]:
        ml[ml.index(i)] = ml[ml.index(i) - 1]
df.columns = ml
df = df.iloc[1:,:12]
df

,2020-03-11 12:00:00,2020-03-11 12:00:00,2020-03-11 12:00:00,2020-03-11 13:00:00,2020-03-11 13:00:00,2020-03-11 13:00:00,2020-03-11 14:00:00,2020-03-11 14:00:00,2020-03-11 14:00:00,2020-03-11 15:00:00,2020-03-11 15:00:00,2020-03-11 15:00:00
REGION,,,,,,,,,,,,
ABJ,98.5022,98.7591,99.5229,98.9913,99.1147,99.5382,98.9648,98.8156,99.4417,98.9856,98.9342,99.6136
ASB,99.0545,98.841,99.4089,98.8195,98.7032,99.6793,98.5846,98.5838,99.5104,98.3829,98.0231,99.2234
ENG,99.0916,99.0027,99.6194,98.9045,98.8783,99.5615,99.0292,98.9379,99.6527,99.0426,98.7161,99.7299
IBD,99.171,98.8402,99.5237,99.1699,99.1208,99.7586,99.2625,99.1924,99.771,99.2436,99.2321,99.8409
KNO,98.065,98.4485,99.3134,97.3755,98.0567,99.0537,97.4053,97.76,98.9076,97.1283,97.6146,98.9158
LGS,95.8561,96.5828,98.7698,95.7763,96.4874,98.8772,95.4111,96.1407,98.9094,95.7431,96.1184,98.5743
PHC,99.1917,99.2497,99.9129,99.3282,99.2136,99.9352,99.2953,99.1578,99.929,99.1989,99.0745,99.9905

In [111]:
import pandas as pd
nam = "Hourly and National Regional Availability_new_2020031117_40f7e54eb61b49338a024de454c3787e.xlsx"
df  = pd.read_excel(f"D:\\2020\\Python\\MTN\MAPS_Availbilty\\Input\\{nam}", sheet_name=0, index_col=None, na_values=['NA'], skiprows=1)
df = df.set_index("REGION")
# df
df.fillna('')

ml = df.columns.tolist()

for i in ml:
    if "Unnamed" in i and "Time" not in ml[ml.index(i) + 1]:
        ml[ml.index(i)] = ml[ml.index(i) - 1]
df.columns = ml
df = df.iloc[1:,:12]
# df.index.tolist()[3]
# df.columns.tolist()[2]

times,regions,techs = df.columns.tolist(),df.index.tolist(),["2G","3G","4G"]
techs = techs * (len(times)//len(techs))
count = 0

for tech,time in zip(techs,times):
    for region in range(len(regions)):
#         print(f'Time is {time}, Region is {regions[region]}, Availability is {"{0:.2f}".format(df.iloc[region,count%12])}, and Technology is {tech}')
        print(f'Time is {str(time)[:10]}, Region is {regions[region]}, Availability is {round(float(df.iloc[region,count%12]),2)}, and Technology is {tech}')
    count += 1
print(count)

Time is 2020-03-11, Region is ABJ, Availability is 98.5, and Technology is 2G
Time is 2020-03-11, Region is ASB, Availability is 99.05, and Technology is 2G
Time is 2020-03-11, Region is ENG, Availability is 99.09, and Technology is 2G
Time is 2020-03-11, Region is IBD, Availability is 99.17, and Technology is 2G
Time is 2020-03-11, Region is KNO, Availability is 98.06, and Technology is 2G
Time is 2020-03-11, Region is LGS, Availability is 95.86, and Technology is 2G
Time is 2020-03-11, Region is PHC, Availability is 99.19, and Technology is 2G
Time is 2020-03-11, Region is ABJ, Availability is 98.76, and Technology is 3G
Time is 2020-03-11, Region is ASB, Availability is 98.84, and Technology is 3G
Time is 2020-03-11, Region is ENG, Availability is 99.0, and Technology is 3G
Time is 2020-03-11, Region is IBD, Availability is 98.84, and Technology is 3G
Time is 2020-03-11, Region is KNO, Availability is 98.45, and Technology is 3G
Time is 2020-03-11, Region is LGS, Availability is 96.58, and Technology is 3G
Time is 2020-03-11, Region is PHC, Availability is 99.25, and Technology is 3G
Time is 2020-03-11, Region is ABJ, Availability is 99.52, and Technology is 4G
Time is 2020-03-11, Region is ASB, Availability is 99.41, and Technology is 4G
Time is 2020-03-11, Region is ENG, Availability is 99.62, and Technology is 4G
Time is 2020-03-11, Region is IBD, Availability is 99.52, and Technology is 4G
Time is 2020-03-11, Region is KNO, Availability is 99.31, and Technology is 4G
Time is 2020-03-11, Region is LGS, Availability is 98.77, and Technology is 4G
Time is 2020-03-11, Region is PHC, Availability is 99.91, and Technology is 4G
Time is 2020-03-11, Region is ABJ, Availability is 98.99, and Technology is 2G
Time is 2020-03-11, Region is ASB, Availability is 98.82, and Technology is 2G
Time is 2020-03-11, Region is ENG, Availability is 98.9, and Technology is 2G
Time is 2020-03-11, Region is IBD, Availability is 99.17, and Technology is 2G
Time is 2020-03-11, Region is KNO, Availability is 97.38, and Technology is 2G
Time is 2020-03-11, Region is LGS, Availability is 95.78, and Technology is 2G
Time is 2020-03-11, Region is PHC, Availability is 99.33, and Technology is 2G
Time is 2020-03-11, Region is ABJ, Availability is 99.11, and Technology is 3G
Time is 2020-03-11, Region is ASB, Availability is 98.7, and Technology is 3G
Time is 2020-03-11, Region is ENG, Availability is 98.88, and Technology is 3G
Time is 2020-03-11, Region is IBD, Availability is 99.12, and Technology is 3G
Time is 2020-03-11, Region is KNO, Availability is 98.06, and Technology is 3G
Time is 2020-03-11, Region is LGS, Availability is 96.49, and Technology is 3G
Time is 2020-03-11, Region is PHC, Availability is 99.21, and Technology is 3G
Time is 2020-03-11, Region is ABJ, Availability is 99.54, and Technology is 4G
Time is 2020-03-11, Region is ASB, Availability is 99.68, and Technology is 4G
Time is 2020-03-11, Region is ENG, Availability is 99.56, and Technology is 4G
Time is 2020-03-11, Region is IBD, Availability is 99.76, and Technology is 4G
Time is 2020-03-11, Region is KNO, Availability is 99.05, and Technology is 4G
Time is 2020-03-11, Region is LGS, Availability is 98.88, and Technology is 4G
Time is 2020-03-11, Region is PHC, Availability is 99.94, and Technology is 4G
Time is 2020-03-11, Region is ABJ, Availability is 98.96, and Technology is 2G
Time is 2020-03-11, Region is ASB, Availability is 98.58, and Technology is 2G
Time is 2020-03-11, Region is ENG, Availability is 99.03, and Technology is 2G
Time is 2020-03-11, Region is IBD, Availability is 99.26, and Technology is 2G
Time is 2020-03-11, Region is KNO, Availability is 97.41, and Technology is 2G
Time is 2020-03-11, Region is LGS, Availability is 95.41, and Technology is 2G
Time is 2020-03-11, Region is PHC, Availability is 99.3, and Technology is 2G
Time is 2020-03-11, Region is ABJ, Availability is 98.82, and Technology is 3G
Time is 2020-03-11, Region is ASB, Availability is 98.58, and Technology is 3G
Time is 2020-03-11, Region is ENG, Availability is 98.94, and Technology is 3G
Time is 2020-03-11, Region is IBD, Availability is 99.19, and Technology is 3G
Time is 2020-03-11, Region is KNO, Availability is 97.76, and Technology is 3G
Time is 2020-03-11, Region is LGS, Availability is 96.14, and Technology is 3G
Time is 2020-03-11, Region is PHC, Availability is 99.16, and Technology is 3G
Time is 2020-03-11, Region is ABJ, Availability is 99.44, and Technology is 4G
Time is 2020-03-11, Region is ASB, Availability is 99.51, and Technology is 4G
Time is 2020-03-11, Region is ENG, Availability is 99.65, and Technology is 4G
Time is 2020-03-11, Region is IBD, Availability is 99.77, and Technology is 4G
Time is 2020-03-11, Region is KNO, Availability is 98.91, and Technology is 4G
Time is 2020-03-11, Region is LGS, Availability is 98.91, and Technology is 4G
Time is 2020-03-11, Region is PHC, Availability is 99.93, and Technology is 4G
Time is 2020-03-11, Region is ABJ, Availability is 98.99, and Technology is 2G
Time is 2020-03-11, Region is ASB, Availability is 98.38, and Technology is 2G
Time is 2020-03-11, Region is ENG, Availability is 99.04, and Technology is 2G
Time is 2020-03-11, Region is IBD, Availability is 99.24, and Technology is 2G
Time is 2020-03-11, Region is KNO, Availability is 97.13, and Technology is 2G
Time is 2020-03-11, Region is LGS, Availability is 95.74, and Technology is 2G
Time is 2020-03-11, Region is PHC, Availability is 99.2, and Technology is 2G
Time is 2020-03-11, Region is ABJ, Availability is 98.93, and Technology is 3G
Time is 2020-03-11, Region is ASB, Availability is 98.02, and Technology is 3G
Time is 2020-03-11, Region is ENG, Availability is 98.72, and Technology is 3G
Time is 2020-03-11, Region is IBD, Availability is 99.23, and Technology is 3G
Time is 2020-03-11, Region is KNO, Availability is 97.61, and Technology is 3G
Time is 2020-03-11, Region is LGS, Availability is 96.12, and Technology is 3G
Time is 2020-03-11, Region is PHC, Availability is 99.07, and Technology is 3G
Time is 2020-03-11, Region is ABJ, Availability is 99.61, and Technology is 4G
Time is 2020-03-11, Region is ASB, Availability is 99.22, and Technology is 4G
Time is 2020-03-11, Region is ENG, Availability is 99.73, and Technology is 4G
Time is 2020-03-11, Region is IBD, Availability is 99.84, and Technology is 4G
Time is 2020-03-11, Region is KNO, Availability is 98.92, and Technology is 4G
Time is 2020-03-11, Region is LGS, Availability is 98.57, and Technology is 4G
Time is 2020-03-11, Region is PHC, Availability is 99.99, and Technology is 4G
12

In [72]:
import os
os.getcwd()

'C:\\Users\\uwx815001'

In [99]:
import pandas as pd
nam = "Hourly and National Regional Availability_new_2020031117_40f7e54eb61b49338a024de454c3787e.xlsx"
df  = pd.read_excel(f"D:\\2020\\Python\\MTN\MAPS_Availbilty\\Input\\{nam}", index_col=None, na_values=['NA'], skiprows=1)

df = df.iloc[:4,14:19]
df = df.set_index("Time")
df

                     Country  2G AVAIL(%)  3G AVAIL(%)  4G AVAIL(%)
Time
2020-03-11 12:00:00  Nigeria        98.79        98.29        99.38
2020-03-11 13:00:00  Nigeria        98.75        98.30        99.45
2020-03-11 14:00:00  Nigeria        98.76        98.12        99.43
2020-03-11 15:00:00  Nigeria        98.74        98.03        99.38

In [103]:
import pandas as pd
nam = "Hourly and National Regional Availability_new_2020031117_40f7e54eb61b49338a024de454c3787e.xlsx"
df  = pd.read_excel(f"D:\\2020\\Python\\MTN\MAPS_Availbilty\\Input\\{nam}", index_col=None, na_values=['NA'], skiprows=1)

df = df.iloc[:4,14:19]
df = df.set_index("Time")
df

times,country,techs = df.index.tolist(),"Nigeria",["2G","3G","4G"]
count = 1

for tech in techs:
    for time in range(len(times)):
        print(f'Time is {str(times[time])[:10]}, Country is {country}, Availability is {"{0:.2f}".format(df.iloc[time,count%4])}, and Technology is {tech}')
    count += 1
print(count)

Time is 2020-03-11, Country is Nigeria, Availability is 98.79, and Technology is 2G
Time is 2020-03-11, Country is Nigeria, Availability is 98.75, and Technology is 2G
Time is 2020-03-11, Country is Nigeria, Availability is 98.76, and Technology is 2G
Time is 2020-03-11, Country is Nigeria, Availability is 98.74, and Technology is 2G
Time is 2020-03-11, Country is Nigeria, Availability is 98.29, and Technology is 3G
Time is 2020-03-11, Country is Nigeria, Availability is 98.30, and Technology is 3G
Time is 2020-03-11, Country is Nigeria, Availability is 98.12, and Technology is 3G
Time is 2020-03-11, Country is Nigeria, Availability is 98.03, and Technology is 3G
Time is 2020-03-11, Country is Nigeria, Availability is 99.38, and Technology is 4G
Time is 2020-03-11, Country is Nigeria, Availability is 99.45, and Technology is 4G
Time is 2020-03-11, Country is Nigeria, Availability is 99.43, and Technology is 4G
Time is 2020-03-11, Country is Nigeria, Availability is 99.38, and Technology is 4G
4

In [104]:
import pandas as pd
nam = "Hourly and National Regional Availability_new_2020031117_40f7e54eb61b49338a024de454c3787e.xlsx"
df  = pd.read_excel(f"D:\\2020\\Python\\MTN\MAPS_Availbilty\\Input\\{nam}", sheet_name=0, index_col=None, na_values=['NA'], skiprows=1)
df = df.set_index("REGION")
df.fillna('')
df

,2020-03-11 12:00:00,Unnamed: 2,Unnamed: 3,2020-03-11 13:00:00,Unnamed: 5,Unnamed: 6,2020-03-11 14:00:00,Unnamed: 8,Unnamed: 9,2020-03-11 15:00:00,Unnamed: 11,Unnamed: 12,Unnamed: 13,Time,Country,2G AVAIL(%),3G AVAIL(%),4G AVAIL(%)
REGION,,,,,,,,,,,,,,,,,,
NaN,2G AVAIL(%),3G AVAIL(%),4G AVAIL(%),2G AVAIL(%),3G AVAIL(%),4G AVAIL(%),2G AVAIL(%),3G AVAIL(%),4G AVAIL(%),2G AVAIL(%),3G AVAIL(%),4G AVAIL(%),NaN,2020-03-11 12:00:00,Nigeria,98.79,98.29,99.38
ABJ,98.5022,98.7591,99.5229,98.9913,99.1147,99.5382,98.9648,98.8156,99.4417,98.9856,98.9342,99.6136,NaN,2020-03-11 13:00:00,Nigeria,98.75,98.30,99.45
ASB,99.0545,98.841,99.4089,98.8195,98.7032,99.6793,98.5846,98.5838,99.5104,98.3829,98.0231,99.2234,NaN,2020-03-11 14:00:00,Nigeria,98.76,98.12,99.43
ENG,99.0916,99.0027,99.6194,98.9045,98.8783,99.5615,99.0292,98.9379,99.6527,99.0426,98.7161,99.7299,NaN,2020-03-11 15:00:00,Nigeria,98.74,98.03,99.38
IBD,99.171,98.8402,99.5237,99.1699,99.1208,99.7586,99.2625,99.1924,99.771,99.2436,99.2321,99.8409,NaN,NaT,NaN,NaN,NaN,NaN
KNO,98.065,98.4485,99.3134,97.3755,98.0567,99.0537,97.4053,97.76,98.9076,97.1283,97.6146,98.9158,NaN,NaT,NaN,NaN,NaN,NaN
LGS,95.8561,96.5828,98.7698,95.7763,96.4874,98.8772,95.4111,96.1407,98.9094,95.7431,96.1184,98.5743,NaN,NaT,NaN,NaN,NaN,NaN
PHC,99.1917,99.2497,99.9129,99.3282,99.2136,99.9352,99.2953,99.1578,99.929,99.1989,99.0745,99.9905,NaN,NaT,NaN,NaN,NaN,NaN

In [33]:
import pandas as pd
nam = "Hourly and National Regional Availability_new_2020031117_40f7e54eb61b49338a024de454c3787e.xlsx"
df  = pd.read_excel(f"D:\\2020\\Python\\MTN\MAPS_Availbilty\\Input\\{nam}", sheet_name=0, index_col=None, na_values=['NA'], skiprows=1)
df = df.set_index("REGION")
# df
df.fillna('')

ml = df.columns.tolist()

for i in ml:
    if "Unnamed" in i and "Time" not in ml[ml.index(i) + 1]:
        ml[ml.index(i)] = ml[ml.index(i) - 1]
df.columns = ml
df = df.iloc[1:,:12]

times,regions,techs = df.columns.tolist(),df.index.tolist(),["2G","3G","4G"]
time,control = times[len(times)//2],[0,1,2]

count = 0


for region in range(len(regions)):
    for tech in techs:
        print(f'Time is {str(time)[:10]}, Region is {regions[region]}, Availability is {round(float(sum(df.iloc[region,list(range(12))[count%3::3]].tolist())/4),2)}, and Technology is {tech}')
        count += 1

count = 0

for region in range(len(regions)):
# for tech in techs:
    avails = [round(float(sum(df.iloc[region,list(range(12))[count%3::3]].tolist())/4),2),round(float(sum(df.iloc[region,list(range(12))[(count+1)%3::3]].tolist())/4),2),round(float(sum(df.iloc[region,list(range(12))[(count+2)%3::3]].tolist())/4),2)]
    print(f'Time is {str(time)[:10]}, Region is {regions[region]}, Availability is {avails}, and Technology is {techs}')
#     count += 1
print(count)

Time is 2020-03-11, Region is ABJ, Availability is 98.86, and Technology is 2G
Time is 2020-03-11, Region is ABJ, Availability is 98.91, and Technology is 3G
Time is 2020-03-11, Region is ABJ, Availability is 99.53, and Technology is 4G
Time is 2020-03-11, Region is ASB, Availability is 98.71, and Technology is 2G
Time is 2020-03-11, Region is ASB, Availability is 98.54, and Technology is 3G
Time is 2020-03-11, Region is ASB, Availability is 99.46, and Technology is 4G
Time is 2020-03-11, Region is ENG, Availability is 99.02, and Technology is 2G
Time is 2020-03-11, Region is ENG, Availability is 98.88, and Technology is 3G
Time is 2020-03-11, Region is ENG, Availability is 99.64, and Technology is 4G
Time is 2020-03-11, Region is IBD, Availability is 99.21, and Technology is 2G
Time is 2020-03-11, Region is IBD, Availability is 99.1, and Technology is 3G
Time is 2020-03-11, Region is IBD, Availability is 99.72, and Technology is 4G
Time is 2020-03-11, Region is KNO, Availability is 97.49, and Technology is 2G
Time is 2020-03-11, Region is KNO, Availability is 97.97, and Technology is 3G
Time is 2020-03-11, Region is KNO, Availability is 99.05, and Technology is 4G
Time is 2020-03-11, Region is LGS, Availability is 95.7, and Technology is 2G
Time is 2020-03-11, Region is LGS, Availability is 96.33, and Technology is 3G
Time is 2020-03-11, Region is LGS, Availability is 98.78, and Technology is 4G
Time is 2020-03-11, Region is PHC, Availability is 99.25, and Technology is 2G
Time is 2020-03-11, Region is PHC, Availability is 99.17, and Technology is 3G
Time is 2020-03-11, Region is PHC, Availability is 99.94, and Technology is 4G
Time is 2020-03-11, Region is ABJ, Availability is [98.86, 98.91, 99.53], and Technology is ['2G', '3G', '4G']
Time is 2020-03-11, Region is ASB, Availability is [98.71, 98.54, 99.46], and Technology is ['2G', '3G', '4G']
Time is 2020-03-11, Region is ENG, Availability is [99.02, 98.88, 99.64], and Technology is ['2G', '3G', '4G']
Time is 2020-03-11, Region is IBD, Availability is [99.21, 99.1, 99.72], and Technology is ['2G', '3G', '4G']
Time is 2020-03-11, Region is KNO, Availability is [97.49, 97.97, 99.05], and Technology is ['2G', '3G', '4G']
Time is 2020-03-11, Region is LGS, Availability is [95.7, 96.33, 98.78], and Technology is ['2G', '3G', '4G']
Time is 2020-03-11, Region is PHC, Availability is [99.25, 99.17, 99.94], and Technology is ['2G', '3G', '4G']
0

In [32]:
import pandas as pd
nam = "Hourly and National Regional Availability_new_2020031117_40f7e54eb61b49338a024de454c3787e.xlsx"
df  = pd.read_excel(f"D:\\2020\\Python\\MTN\MAPS_Availbilty\\Input\\{nam}", index_col=None, na_values=['NA'], skiprows=1)

df = df.iloc[:4,14:19]
df = df.set_index("Time")
df

times,country,techs = df.index.tolist(),"Nigeria",["2G","3G","4G"]
count = 1
avails = []

for tech in techs:
#     for time in range(len(times)):
    print(df.iloc[:,count%4].tolist())
#     print(f'Time is {str(times[time])[:10]}, Country is {country}, Availability is {"{0:.2f}".format(round(float(sum(df.iloc[:,count%4].tolist())/4)),2)}, and Technology is {tech}')
    print(f'Time is {str(times[len(times)//2])[:10]}, Country is {country}, Availability is {round(float(sum(df.iloc[:,count%4].tolist())/4),2)}, and Technology is {tech}')
    avails.append(round(float(sum(df.iloc[:,count%4].tolist())/4),2))
    count += 1
print(count)
print(avails)

[98.79, 98.75, 98.76, 98.74]
Time is 2020-03-11, Country is Nigeria, Availability is 98.76, and Technology is 2G
[98.29, 98.3, 98.12, 98.03]
Time is 2020-03-11, Country is Nigeria, Availability is 98.19, and Technology is 3G
[99.38, 99.45, 99.43, 99.38]
Time is 2020-03-11, Country is Nigeria, Availability is 99.41, and Technology is 4G
4
[98.76, 98.19, 99.41]

In [15]:
import pandas as pd
nam = "Hourly and National Regional Availability_new_2020031117_40f7e54eb61b49338a024de454c3787e.xlsx"
df  = pd.read_excel(f"D:\\2020\\Python\\MTN\MAPS_Availbilty\\Input\\{nam}", index_col=None, na_values=['NA'], skiprows=1)

df = df.iloc[:4,14:19]
df = df.set_index("Time")
print(df)
print(df.iloc[:,1].tolist())

                     Country  2G AVAIL(%)  3G AVAIL(%)  4G AVAIL(%)
Time
2020-03-11 12:00:00  Nigeria        98.79        98.29        99.38
2020-03-11 13:00:00  Nigeria        98.75        98.30        99.45
2020-03-11 14:00:00  Nigeria        98.76        98.12        99.43
2020-03-11 15:00:00  Nigeria        98.74        98.03        99.38
[98.79, 98.75, 98.76, 98.74]